Update robotium jar version Fixes #4
Due to some bug in robotium 4.1 version, the following error kept creeping up
during instrumentation tests.
> java.lang.ClassCastException: java.util.ArrayList cannot be cast to
> android.view.View[]

Updating robotium jar seemed to resolve the issue.

Signed-off-by: Venkatesh Shukla <venkatesh.shukla.eee11@iitbhu.ac.in>